# Generated by Django 4.2.4 on 2023-08-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='pass_book',
            new_name='cheque_book',
        ),
    ]
