# Generated by Django 4.2.2 on 2023-06-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='pic')),
                ('details', models.TextField()),
            ],
        ),
    ]
